#
# ######################################################################################
# # LGPL License                                                                       #
# #                                                                                    #
# # This file is part of the LightJason AgentSpeak(L++) Traffic-Simulation             #
# # Copyright (c) 2017, LightJason (info@lightjason.org)                               #
# # This program is free software: you can redistribute it and/or modify               #
# # it under the terms of the GNU Lesser General Public License as                     #
# # published by the Free Software Foundation, either version 3 of the                 #
# # License, or (at your option) any later version.                                    #
# #                                                                                    #
# # This program is distributed in the hope that it will be useful,                    #
# # but WITHOUT ANY WARRANTY; without even the implied warranty of                     #
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                      #
# # GNU Lesser General Public License for more details.                                #
# #                                                                                    #
# # You should have received a copy of the GNU Lesser General Public License           #
# # along with this program. If not, see http://www.gnu.org/licenses/                  #
# ######################################################################################
#

# main definition
main:
    simulationspeed: 500
    messagedelay:
      default: 3500
      agentprint: 2500


# agent definition (asl is relative to search path)
agent:
    environment:
      visible: false
    communication:
      visible: false
    area:
      visible: false
    defaultvehicle:
      visible: false


# HTTP server binding for UI
ui:
    openbrowser: true
    port: 12345
    host: localhost
    cookieexpire_in_seconds: 120

# simulation units
units:
    cellsize_in_meter: 3.5
    time_in_minutes: 0.5

